var status = {
    PLAYER_WAITING: "PLAYER WAITING",
    PLAYER_READY: "PLAYER READY",
    PLAYER_NOT_READY: "PLAYER NOT READY",
    PLAYER_LEFT: "PLAYER LEFT",
    GAME_IN_PROGRESS: "GAME IN PROGRESS",
    GAME_STARTED: "GAME STARTED",
    GAME_NOT_STARTED: "GAME NOT STARTED",
    GAME_ENDED: "GAME ENDED",
    BOARD_IN_PROGRESS: "BOARD IN PROGRESS",
    BOARD_STARTED: "BOARD STARTED",
    BOARD_NOT_STARTED: "BOARD NOT STARTED",
    BOARD_ENDED: "BOARD ENDED"
}
module.exports = status;
